### ISSUE TITLE
Hangout 2016-02 (Organización)

### ISSUE THREAD

**Issue by carlosgruiz-dev** [pyve/documentos#3]
## Fechas Propuestas

del 23 al 25 de Febrero (con preferencia al 24)

Votaciones para la fecha y hora en [doodle](http://doodle.com/poll/emywza5dk2pzfxe4)
## Temas para seguimiento
- Facturero de la Fundación
- Propuesta de imagen institucional de la fundación
- Resultados de 1er PyDay 2016 (PyTatuy) 
- Avances y propuestas para página web
- Avances y propuestas en mecanismos de comunicación
- Confirmar con @talueses su propuesta para traducciones
## Temas nuevos

**[Por incorporar]**

**Comment by hernanramirez** [comment]
puedo el 24 o 25 a las 8pm

**Comment by hernanramirez** [comment]
Quiero proponer hacer una asamblea de miembros de la fundación para: 
- Sumar nuevos miembros
- Discutir coutas de membrecías
- Definir plan de trabajo sobre finanzas y elaboración de factureros.

Las decisiones de la fundación la define la asamblea tal como reza e documento :-)

**Comment by flaper87** [comment]
Agregué un link para las votaciones en la descripción. Lo pego aquí de nuevo: http://doodle.com/poll/emywza5dk2pzfxe4

**Comment by nhomar** [comment]
- Entregar sitio admin.python.info.ve para la gestión de administración

**Comment by nhomar** [comment]
https://plus.google.com/hangouts/_/jylqaos6hba27ar3dl2kvv5p6ma
